# Generated by Django 2.1.7 on 2019-04-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='products_images/preview', verbose_name='Картинка категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='products_images/preview', verbose_name='Картинка подкатегории'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание подкатегории'),
        ),
    ]
