# Generated by Django 2.1.7 on 2019-04-06 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(blank=True, max_length=25, verbose_name='Артикул'),
        ),
    ]
