# Generated by Django 2.1.7 on 2019-04-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='nesting_level',
            field=models.IntegerField(default=0),
        ),
    ]
