# Generated by Django 2.1.7 on 2019-04-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190402_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(blank=True, upload_to='products_images/preview', verbose_name='Preview'),
        ),
    ]
