# Generated by Django 2.1.7 on 2019-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190418_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nesting_level',
            field=models.IntegerField(default=0),
        ),
    ]
