# Generated by Django 2.1.7 on 2019-04-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20190428_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='email'),
        ),
    ]
