# Generated by Django 2.1.7 on 2019-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_shopuserprofile_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='somefield',
            field=models.CharField(blank=True, max_length=128, verbose_name='ещё какое-то поле'),
        ),
    ]
