# Generated by Django 2.1.7 on 2019-05-04 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_shopuserprofile_somefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuserprofile',
            name='somefield',
        ),
    ]
