# Generated by Django 2.1.7 on 2019-05-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_remove_shopuserprofile_somefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_link',
            field=models.URLField(blank=True, max_length=256, verbose_name='Ссылка на профиль VK'),
        ),
    ]
