# Generated by Django 2.1.7 on 2019-05-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_shopuserprofile_vk_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_photo',
            field=models.URLField(blank=True, max_length=512, verbose_name='Ссылка на фото VK'),
        ),
    ]
